plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails
AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - .bundle/**/*
    - vendor/**/*
  NewCops: enable
Style/Documentation:
  Enabled: false
