on:
  workflow_call:
jobs:
  haml-lint:
    name: lib
    uses: umts/shared-workflows/.github/workflows/haml-lint.yml@main
  oxfmt:
    name: lib
    uses: umts/shared-workflows/.github/workflows/oxfmt.yml@main
  oxlint:
    name: lib
    uses: umts/shared-workflows/.github/workflows/oxlint.yml@main
  rspec:
    name: lib
    uses: umts/shared-workflows/.github/workflows/rspec.yml@main
    with:
      node: true
      setup_command: "bin/rails css:build"
  rubocop:
    name: lib
    uses: umts/shared-workflows/.github/workflows/rubocop.yml@main
  stylelint:
    name: lib
    uses: umts/shared-workflows/.github/workflows/stylelint.yml@main
